'use client'

import {
  LayoutDashboard,
  ShoppingBag,
  Users,
  ClipboardList,
  BarChart3,
  Settings,
  HelpCircle,
  ChevronRight,
  LogOut,
  Ticket,
  Package,
  Search,
  Tag,
  ChevronLeft,
  CircleUser,
  Home,
  Store,
  Plus,
  ImageIcon,
  FileText,
  CreditCard,
  UserCheck,
  Bell,
  PlusCircle,
  List,
  FolderPlus,
  Grid,
  Tags,
  Boxes,
  Building,
  TicketPlus,
  Moon,
  Sun,
  Shirt,
  Edit,
  Trash2,
  Heart,
  ShoppingCart,
  X,
  Check,
  AlertTriangle,
  Menu,
  ChevronUp,
  ChevronDown,
} from 'lucide-react'

export const Icons = {
  // Dashboard
  Dashboard: LayoutDashboard,
  Products: Package,
  Users: Users,
  Orders: ClipboardList,
  Analytics: BarChart3,
  Settings: Settings,
  Support: HelpCircle,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ChevronUp: ChevronUp,
  ChevronDown: ChevronDown,
  LogOut: LogOut,
  Ticket: Ticket,
  Search: Search,
  Tag: Tag,
  User: CircleUser,
  Home: Home,
  Store: Store,
  Plus: Plus,
  Image: ImageIcon,
  File: FileText,
  Payment: CreditCard,
  UserCheck: UserCheck,
  Bell: Bell,
  PlusCircle: PlusCircle,
  List: List,
  FolderPlus: FolderPlus,
  Grid: Grid,
  Tags: Tags,
  Boxes: Boxes,
  Building: Building,
  TicketPlus: TicketPlus,
  Moon: Moon,
  Sun: Sun,
  Shirt: Shirt,
  Edit: Edit,
  Delete: Trash2,
  Heart: Heart,
  Cart: ShoppingCart,
  Close: X,
  Check: Check,
  Warning: AlertTriangle,
  Menu: Menu,
}

export default Icons
